Repository Git-For-Geeks/Data-Structures-and-Algorithms, pull requests merged in 2022-10, with the labels that each got.

#21 testing
  testing
Labels: git-for-geeks, easy

#24 adding mathematics-problem-4
  Mathematics/4_Integer_to_Roman.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted

#27 adding mathematics 4
  Mathematics/4_Integer_to_Roman.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted

#45 2_Kth_smallest_element
  Arrays/2_Kth_smallest_element.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#39 Yash14agr
  .vscode/settings.json
  LinkedList/Implement_Linked_List_in_c++.cpp
  Problems.md
  testing
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#51 first commit
  Sorting and Searching/9_Bubble_Sort.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#52 Chandakrohit8
  Arrays/2_Kth_smallest_element.cpp
  Strings/2_Longest_Palindromic_Substring.cpp
Labels: git-for-geeks, hacktoberfest-accepted, medium, hacktoberfest

#50 Added Array/4_Two_sum
  Arrays/2_Kth_smallest_element.cpp
  Arrays/4_Two_Sum.java
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#53 Union of array problem solved
  Arrays/Union_of_two_arrays.cpp
Labels: git-for-geeks, hacktoberfest-accepted, medium, hacktoberfest

#54 LinkedList Problem Solved
  Arrays/LinkedList/Implementation.c
Labels: git-for-geeks, hacktoberfest-accepted, medium, hacktoberfest

#56 Solution for 3Sum
  Arrays/5_3Sum.cpp
  Sorting and Searching/17_sort_colors.cpp
Labels: git-for-geeks, hacktoberfest-accepted, medium, hacktoberfest

#62 Solution of 6 (Two Elevators)
  Mathematics/6_Two_Elevators.c++
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#63 Sansgupta25
  .vscode/tasks.json
  Arrays/median_of_two_sorted_arrays.cpp
Labels: git-for-geeks, hacktoberfest-accepted, medium, hacktoberfest

#65 Solution for implementation of stack in Python
  Implment Stack in Python.py
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#66 linearsearch code added
  Sorting and Searching/1_linearsearch.c
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#76 Sansgupta25- Deleting a node in linked list
  Linked list/delete_a_node_from_ll.cpp
Labels: git-for-geeks, hacktoberfest-accepted, medium, hacktoberfest

#89 Added solution
  Mathematics/11_Roman_To_Integer.java
Labels: git-for-geeks, hacktoberfest-accepted, medium, hacktoberfest

#91 Implement Stack in C++.cpp
  Stack/Implement Stack in C++.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#93 Stack Implemented in Java
  Stack/3_Implement_Stack_in_java.java
Labels: git-for-geeks, hacktoberfest-accepted, medium, hacktoberfest

#105 yash14agr
  LinkedList/.vscode/settings.json
  LinkedList/2_Implement_Linked_List_in_c++.cpp
  LinkedList/5_Reverse_Linked_List.c
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#106 Sansgupta25-linear search in c
  Searching/linear_search.c
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#113 Implemented Linear search in java
  Sorting-and-Searching/3_Implement_Linear_Search_In_Java.java
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#121 adding DP QUE10 RegularExpressionMatching
  Dyanamic_Programing/10_Regular_Expression_Matching.cpp
  Graphs/25_Largest Component Size by Common Factor.cpp
  Trees/10_KthAncestorOfATreeNode.cpp
Labels: git-for-geeks, hacktoberfest-accepted, hacktoberfest, hard

#127 20_of strings
  Strings/20_Integer to English Words of Strings.cpp
Labels: git-for-geeks, hacktoberfest-accepted, hacktoberfest, hard

#123 Strong password checker.py
  Strings/Strong password checker.py
Labels: git-for-geeks, hacktoberfest-accepted, hacktoberfest, hard

#115 Arrays/1_At least two greater elements
  Arrays/1_At_least_two_greater_elements.c++
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#119 Solution For Problem 9 of Sorting and Searching-> Bubble Sort
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  9_Bubble-Sort.java
  Sorting-and-Searching.iml
  out/production/Sorting-and-Searching/.idea/.gitignore
  out/production/Sorting-and-Searching/.idea/misc.xml
  out/production/Sorting-and-Searching/.idea/modules.xml
  out/production/Sorting-and-Searching/.idea/vcs.xml
  out/production/Sorting-and-Searching/Main.class
  out/production/Sorting-and-Searching/Problems.md
  out/production/Sorting-and-Searching/README.md
  out/production/Sorting-and-Searching/Sorting-and-Searching.iml
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#122 Sansgupta25 - queue using two stack
  Queue/Queue using two Stacks.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#124 Added Arrays Problem 9 Matrix Multiply
  Arrays/Multiply_Matrices.C
  Problems.md
Labels: git-for-geeks, hacktoberfest-accepted, hacktoberfest, hard

#125 Tower Of Hanoi
  Arrays/10_subarray_with_given_sum.cpp
  Arrays/10_subarray_with_given_sum.exe
  Arrays/2_Kth_smallest_element.cpp
  Problems.md
  Stack/7_tower_of_hanoi.cpp
  Stack/7_tower_of_hanoi.exe
Labels: git-for-geeks, hacktoberfest-accepted, medium, hacktoberfest

#132 :zap: SiddheshJawadi Solution for Sorting and Searching Problem 19 The_Rank
  Sorting_and_Searching/19_The_Rank.py
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#131 20_Implement_Trie
  Strings/20_Implement_Trie.c++
Labels: git-for-geeks, hacktoberfest-accepted, hacktoberfest, hard

#143 21_Trapping Rain Water
  Arrays/Trapping Rain Water.cpp
Labels: git-for-geeks, hacktoberfest-accepted, hacktoberfest, hard

#133 Solve Next Permutation Leetcode
  Next_Permutation.py
  Problems.md
Labels: git-for-geeks, hacktoberfest-accepted, medium, hacktoberfest

#137 Added Solution for Design an ATM Machine
  Arrays/18_Design_an_ATM_Machine.java
Labels: git-for-geeks, hacktoberfest-accepted, hacktoberfest, hard

#138 Added Linear search in .cpp
  Searching and Sorting/2_Implement_Linear_Search_in_cpp.cpp
  Searching and Sorting/6_Implement_Binary_Search_in_cpp.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#147 22_Trapping Rain Water II
  Arrays/22_Trapping Rain Water(II)_from arrays.cpp
Labels: git-for-geeks, hacktoberfest-accepted, hacktoberfest, hard

#139 Stacks->Problem 1 and Queues->Problem 1
  Problems.md
  Queue/1_Implement_Queue_using_array_in_C.c
  Stack/1_Implement_Stack_in_C.c
Labels: git-for-geeks, hacktoberfest-accepted, hacktoberfest, hard

#144 Implementation Of Linked List in Java
  LinkedList/3_Implement_Linked_List_in_Java.java
Labels: git-for-geeks, hacktoberfest-accepted, hacktoberfest, hard

#152 Sahilhedau49
  Problems.md
  Sorting and Searching/Implement_Binary_Search_in_c++.c++
Labels: git-for-geeks, hacktoberfest-accepted, medium, hacktoberfest

#175 Gaurav_M_kedia
  Stack/6_Longest_Valid_Parentheses.c++
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#185 Implementing_Dijkstra_Algorithm.cpp
  Graphs/Implementing_Dijkstra_Algorithm.cpp
Labels: git-for-geeks, hacktoberfest-accepted, hacktoberfest, hard

#191 Added Sort matrix diagonally.py
  Sort_matrix_diagonally.py
Labels: git-for-geeks, hacktoberfest-accepted, medium, hacktoberfest

#193 5_Valid_Parentheses
  Problems.md
  Stack/5_Valid_Parentheses.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#196 Arrays_24_Sudoku_Solver
  Arrays/24_Sudoku_Solver.java
Labels: git-for-geeks, hacktoberfest-accepted, hacktoberfest, hard

#208 Created CombinationSum.cpp
  Arrays/CombinationSum.cpp
Labels: git-for-geeks, hacktoberfest-accepted, hacktoberfest

#201 10_Longest_Increasing_Subsequence_II
  Queue/10_Longest_Increasing_Subsequence_II.c++
Labels: git-for-geeks, hacktoberfest-accepted, medium, hacktoberfest

#203 Quick Sort
  Arrays/12_Maximum_Subarray_Sum.cpp
  Searching_and_sortingg/Quick_sort.c
  Sorting and Searching/9_Bubble_Sort.cpp
  Sorting_and_Searching/.vscode/settings.json
  Sorting_and_Searching/12_Merge_Sort.c
Labels: git-for-geeks, hacktoberfest-accepted, medium, hacktoberfest

#205 yash14agr
  Stack/.vscode/settings.json
  Stack/9_Longest Valid Parentheses.cpp
Labels: git-for-geeks, hacktoberfest-accepted, medium, hacktoberfest

#215 Quick_sort
  Searching_and_sortingg/Quick_sort.c
Labels: git-for-geeks, hacktoberfest-accepted, medium, hacktoberfest

#212 24_Number_of_Way_Reconstruct_a_Tree
  Trees/24_Number_Of_Ways_To_Reconstruct_a_Tree.java
Labels: git-for-geeks, hacktoberfest-accepted, hacktoberfest, hard

#217 Graphs_16_Build_a_Matrix_with_conditions
  Graphs/16_Build_a_Matrix_with_Conditons.c++
Labels: git-for-geeks, hacktoberfest-accepted, medium, hacktoberfest

#219 9_Longest_Valid_Parentheses
  DynamicProgramming/9_Longest_Valid_Parentheses.c++
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#224 Added Strings Problem 11
  Strings/11_solvetheequation.java
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#225 17_mps
  Arrays/17_Minimum_path_sum.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#226 count_sort
  Searching_and_sorting/countSort.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#228 Solved Min cost to connect all points by kruskal
  Min Cost to Connect All Points by kruskal.py
  Problems.md
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#227 11_Design_a_Text_Editor
  LinkedList/11_Design_a_Text_Editor.c++
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#231 Solution for Best Time to Buy Sell a Stock II
  Dynamic Programming/6_buy_sell_2.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#235 Code to sort the matrix diagonally by divyanshu
  Arrays/14_Sort_the_Matrix_Diagonally.py
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#237 yash14agr
  Sorting and Searching/.vscode/settings.json
  Sorting and Searching/20_Concert_TIckets.cpp
  Sorting and Searching/20_Concert_TIckets.exe
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#252 Added Kosaraju.py
  Kosaraju Algorithm.py
  README.md
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#241 Solution of Accumulation_of_Dominoes
  Mathematics/5_Accumulation_of_Dominoes.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#247 heap sort
  Searching_and_sorting/HeapSort.c
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#251 Added Dynamic Programming->3. Coin Change
  Dynamic_Programming/3_Coin_Change.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#258 2_implement queue
  Queue/2_Implement Queue using array in C++.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#261 Implementation_of_LinkedList_in_Python
  LinkedList/4_Implement_LinkedList_in_Python.py
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#279 radix sort
  Searching_and_sorting/Radix_sort.c
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#288 Longest substring without repeating character
  Sorting and Searching/Implement_Binary_Search_in_Python.py
  Strings/Find_the_Shortest_Superstring.class
  Strings/Find_the_Shortest_Superstring.java
  Strings/Longest_Substring_Without_Repeating_Characters.py
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#289 Added Level order traversal in cpp
  Graphs/14_Level_order_Traversal_in_cpp.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#295 1 Longest Substring Without Repeating Characters from strings
  Strings/1 Longest Substring Without Repeating Characters .cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#297 Sagar Dave
  SagarDave/Dominoes.ipynb
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#299 Solution added to Excel_sheet_column_number
  strings/5_Excel_sheet-column_number.cpp
  strings/New Text Document.txt
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#298 Sagar Dave
  SagarDave/Atm_machine.java
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#312 Sagar Dave
  Problems.md
  SagarDave_2/TwoElevator.ipynb
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#300 Adding Mathematics Folder
  Mathematics/3_Excel_Sheet_Column_Title.java
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#301 Solution for Strings_13_Restore IP address
  sort_and_search/5_binary_search.js
  strings/13_Restore_IP_Address.cpp
  strings/New Text Document.txt
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#302 Nextgreaterelement
  Stack/8_nextgreaterelement.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#311 2_BFS of graph
  Graphs/BFS OF GRAPH.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#310 Counting_coprime_pairs
  Mathematics/Counting_coprime_pairs.py
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#307 yash14agr
  graph/6_DFS_in_C++.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#303 Added Design a Circular Deque
  Design a Circular Deque
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#320 Adding Strings folder
  Strings/10_ Longest_Ideal_Subsequence.java
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#318 Sansgupta25-Stack using queue
  Queue/Stack using queue.c
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#316 Added 4sum.py
  4sum.py
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#321 Adding Graphs folder
  Graphs/20_Longest_Cycle_in_a_Graph.py
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#322 Added Solution for Best Time to Buy a Stock
  Dynamic Programming/5_buySell_1.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#323 6_3Sum Closest_from array
  Arrays/3Sum Closest.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#325 7_4Sum from array
  Arrays/7_4Sum.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#326 10_Postorder Traversal in c++ from trees.
  Trees/10_Postorder Traversal in c++.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#330 16 Range Sum Query - Mutable
  Arrays/16_Range Sum Query - Mutable.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#329 Added Sorting and Searching P-10
  Problems.md
  README.md
  sorting and searching/insertion_sort.c
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#334 reemakhandelwal
  Graphs/12_find_number_of_islands.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#342 20_Merge_Interval
  Arrays/20_Merge Intervals.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#341 Solution added to Implement Binary Search in JS
  sort_and_search/5_binary_search.js
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#344 23_MO'S
  Arrays/23_MO'S_Algo.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#351 9_Reformat The String
  Strings/9_Reformat The String.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#353 12_Longest Substring
  Strings/12_Longest Substring with At Least K Repeating Characters.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#349 Added Coin Change II
  Coin Change II.py
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#348 Solution for Excel sheet column title
  strings/6_Excel_sheet_column_Title.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#346 preordertransversal in java
  Trees/3_preorder_transversa.java
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#356 6_Inorder Traversal in c++ from trees
  Trees/6_Inorder Traversal.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#355 :zap: SiddheshJawadi Solution of Strings Problem 6 Excel Sheet Titles
  Strings/6_Excel_Sheet_Column_Title.py
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#359 Sudoku Solver
  Solve-sudoku.java
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#358 Added 3sumCloset.py
  3sumCloset.py
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#361 yash14agr
  Trees/10_Postorder_Traversal_in_c++.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#364 Path Matrix Finder
  Path Matrix Finder.c
  Stack problem.c
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#365 Minal ghate
  Sorting-and-Searching/16_Countingsort.java
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#367 Reverse a Linked List in Groups
  Linked List/7_reverse_a_LL_in_groups.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#369 20_Lowest_Common_Ancestor_in_a_Binary_Tree.cpp
  Trees/20_Lowest_Common_Ancestor_in_a_Binary_Tree.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#380 Added solution
  Queue/3_ImplementQueueUsingArray.java
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#378 Added Solution for Last Substring in Lexicographical Order
  Strings/14_Last_Substring_in_Lexicographical_Order.java
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#377 Solution for Tower Of Hanoi
  stack/7_Tower_Of_Hanoi.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#371 Added Is Graph Bipartite.py
  Is Graph Bipartite.py
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#376 12_Level-order_Traversal_in_java
  Trees/12_Level-order_Traversal_in_java.java
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#375 Merge 2 BST
  Trees/12_mergeTrees.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#372 :grin: SiddheshJawadi String Problem 9 Reformat The String Solution
  Strings/9_Reformat_The_String.py
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#386 Vedant
  3SumClosest.py
  LevelorderTraversalinPython.py
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#388 Adding Solution of Graph problem 21
  Graphs/21_Min_Cost_to_Connect_All_Points_prims.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#389 Adding Solution of Tree problem 23
  Trees/23_Merge_two_BST.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#390 trappingrainwater
  Queue/9_trappingrainwater.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#398 inorder_traversal
  Trees/6_inorder_traversal.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#399 17_Text_Justification
  Strings/17_Text_Justification.java
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#401 Added solution
  Trees/7_InorderTraversal.java
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#406 10_Delete_Node_in_LinkedList
  LinkedList/10_Delete_Node_in_LinkedList.c++
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#409 3_Combination_Sum
  Arrays/3_Combination_Sum.c++
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#410 Diameter of a binary tree
  Trees/Diameter_of_a_binary_tree.py
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#415 Subsets_II
  Arrays/Subsets_II.c++
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#417 16_Range_Sum_Query_Mutable
  Arrays/16_Range_Sum_Query_Mutable.c++
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#418 Sagar Dave - K- Factorization.
  SagarDave_2/Kfac.ipynb
  SagarDave_2/Pnumbersipynb.ipynb
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#419 Union Of Doubly LinkedList
  LinkedList/8_UnionOfDoublyLinkedList.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#421 Tower of Hanoi
  Stacks/Tower_OF_Hanoi.py
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#422 11_Solve_the_equation
  Strings/11_Solve_the_equation.c++
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#425 8_Count_Binary_Substring
  Strings/8_Count_Binary_Substring.c++
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#427 Text Editor
  Strings/18_TextEditor.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#431 4_Coin_Change_II
  DynamicProgramming/4_Coin_Change_II.c++
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#432 Preorder Traveral in c
  Trees/Preorder_Traversal_in_c.c
  Trees/Preorder_Traversal_in_c.exe
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#437 Added solution
  Trees/15_LevelOrderTraversal.java
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#435 SumClosest
  Arrays/6_SumClosest.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#439 20_Longest_Cycle_in_a_Graph
  Graphs/20_Longest_Cycle_in_a_Graph.c++
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#441 Inorder Traversal in c
  Trees/Inorder_traversal_in_c.c
  Trees/Inorder_traversal_in_c.exe
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#440 Subsets_II
  Arrays/15_subsets.py
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#448 22_Recover a Tree From Preorder Traversal
  Trees/22_Recover a Tree From Preorder Traversal.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#443 2_Preorder_Traversal
  Trees/2_Preorder_Traversal.c++
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#450 Linked List with Inserting and Deleting in C
  Even and Odd list of LinkedList using C.c
  Implementation of two stack in an Array in C.c
  LinkedList.c
  Mirror of Binary tree using C.c
  Stack using LinkedList in C++.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#452 8 Best Time to Buy and Sell Stock IV from graphs
  Trees/8 Best Time to Buy and Sell Stock IV.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#455 Adding problem 9 of Graph
  Graphs/9_Print_adjacency_list.cpp
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#460 ZigZag tree Traversal
  Trees/Inorder_traversal_in_c.c
  Trees/ZigZag_tree_traversal.py
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#461 Added solution
  Graphs/3_BFSofGraph.java
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest

#463 7_Verifying_an_Alien_Dictionary
  Strings/7_Verifying_an_Alien_Dictionary.c++
Labels: git-for-geeks, easy, hacktoberfest-accepted, hacktoberfest
